services:
  - type: web
    name: lostfound-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt && python backend/manage.py collectstatic --noinput"
    startCommand: "cd backend && gunicorn lostfound.wsgi:application --bind 0.0.0.0:$PORT"
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: lostfound-db
          property: connectionString
  - type: pserv
    name: lostfound-db
    env: postgres
    plan: free